"""add deployment_environment marker table

Revision ID: d29753436024
Revises: 825a4116c834
Create Date: 2026-08-13 20:10:00.000000+00:00

An app taking this by `copier update` must repoint `down_revision` at its own
current head — 825a4116c834 is the template's initial revision and exists only
in a freshly stamped app. Left unrepointed, alembic raises
`KeyError: '825a4116c834'` while building its revision map, which surfaces as a
pytest INTERNALERROR rather than a migration error.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d29753436024"
down_revision: str | None = "825a4116c834"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deployment_environment",
        sa.Column("id", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column(
            "stamped_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("id IS TRUE", name="ck_deployment_environment_single_row"),
        sa.CheckConstraint(
            "environment IN ('production', 'local')",
            name="ck_deployment_environment_known_value",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deployment_environment")
    # ### end Alembic commands ###
