/**
 * `$app/environment`, for the unit runner only.
 *
 * `sveltekit-superforms`' entry point re-exports `SuperDebug.svelte`, which
 * imports `$app/environment` and `$app/stores`. Those are generated by
 * `svelte-kit sync` inside an APP, and this package is a library — there is no
 * app around it and no generated module to resolve. The form wrappers
 * themselves touch neither; they arrive only through that barrel.
 *
 * Stubbed rather than mocked per test: it is a build-time resolution problem,
 * not a behaviour anything here asserts.
 */
export const browser = true;
export const dev = true;
export const building = false;
export const version = 'test';
