/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current User
         * @description Return the caller's own user record and this request's entitlements.
         *
         *     The SPA calls this once at startup to populate its auth store. There is no
         *     route to list or read OTHER users: the app is not a directory, and the
         *     identity provider already is one.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Workspaces
         * @description List the workspaces the caller belongs to, with their role in each.
         *
         *     Always at least one — every user is provisioned a personal workspace on first
         *     sight. The SPA calls this at startup and renders a switcher only when the
         *     list has more than one entry.
         */
        get: operations["listMyWorkspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Workspace
         * @description Create a workspace. The caller becomes its owner.
         */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename Workspace
         * @description Rename a workspace. Owner only. The slug is stable and does not follow.
         */
        patch: operations["renameWorkspace"];
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Member
         * @description Grant someone membership of a workspace. Owner only.
         *
         *     This is the act the whole primitive exists for: sharing is a grant somebody
         *     makes, never something the app infers from two people using the same proxy.
         */
        post: operations["addWorkspaceMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Member
         * @description Retract someone's membership. Owner only.
         *
         *     Their rows stay with the workspace and their attribution stays on them; only
         *     the grant goes.
         */
        delete: operations["removeWorkspaceMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/example/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Items
         * @description List all example items.
         */
        get: operations["listExampleItems"];
        put?: never;
        /**
         * Create Item
         * @description Create a new example item.
         */
        post: operations["createExampleItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/example/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Item
         * @description Get a single example item by id.
         */
        get: operations["getExampleItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Report liveness and verify the database dependency.
         *
         *     Pings the database with `SELECT 1`; a 503 is the only outcome that
         *     should fail a load balancer's health check, so every other dependency
         *     this app grows should degrade the body, never this status code.
         *
         *     Raises:
         *         ServiceUnavailableError: the database is unreachable (503).
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/database-environment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Database Environment
         * @description Report what the database this backend is bound to declares itself to be.
         *
         *     The one thing a caller talking to this backend over HTTP — rather than
         *     holding a connection of its own — can ask to find out what it is really
         *     about to write to. `db/environment.py`'s reasoning applies unchanged:
         *     unstamped or unreachable reads as production, fail-closed.
         *
         *     No auth dependency, matching /health: a caller that cannot yet tell which
         *     database it has reached is in no position to authenticate against it, and
         *     the answer names an environment, never a host or a credential.
         */
        get: operations["databaseEnvironment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CurrentUserRead
         * @description The caller's own record, plus the entitlements this request carried.
         *
         *     Entitlements are NOT persisted — they arrive in a header on every request and
         *     are true only of the request that carried them. Serving them here is what lets
         *     the SPA hide a module the caller cannot reach; it is a convenience for the UI,
         *     never the gate. The gate is ``require_module()`` on the server.
         */
        CurrentUserRead: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string | null;
            /** Is Admin */
            is_admin: boolean;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Entitlements */
            entitlements: string[];
        };
        /**
         * DatabaseEnvironmentResponse
         * @description What the running backend's database declares itself to be.
         */
        DatabaseEnvironmentResponse: {
            /** Environment */
            environment: string;
        };
        /**
         * ExampleItemCreate
         * @description Request body for creating an ExampleItem.
         */
        ExampleItemCreate: {
            /** Title */
            title: string;
            /** Body */
            body?: string | null;
        };
        /**
         * ExampleItemRead
         * @description Response schema for ExampleItem (excludes internal DB columns).
         */
        ExampleItemRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Body */
            body: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response body.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * MemberAdd
         * @description Request body for granting someone membership of a workspace.
         *
         *     Identified by the app's own user id rather than an Authentik uid: the caller
         *     granting access is choosing from people the app already knows, and accepting
         *     a provider key here would let a client mint a membership for an identity the
         *     app has never authenticated.
         */
        MemberAdd: {
            /** User Id */
            user_id: number;
            /** @default member */
            role: components["schemas"]["WorkspaceRole"];
        };
        /**
         * MembershipRead
         * @description One of the caller's memberships, with the workspace it grants.
         *
         *     This is what the SPA's workspace switcher renders, and what tells it whether
         *     to render at all: a caller with one membership never sees a switcher.
         */
        MembershipRead: {
            workspace: components["schemas"]["WorkspaceRead"];
            role: components["schemas"]["WorkspaceRole"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkspaceCreate
         * @description Request body for creating a workspace. The creator becomes its owner.
         */
        WorkspaceCreate: {
            /** Name */
            name: string;
        };
        /**
         * WorkspaceRead
         * @description A workspace as the API exposes it.
         */
        WorkspaceRead: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /**
         * WorkspaceRename
         * @description Request body for renaming a workspace. Owner only.
         */
        WorkspaceRename: {
            /** Name */
            name: string;
        };
        /**
         * WorkspaceRole
         * @description A member's standing IN a workspace — never what they may do in a module.
         *
         *     Module read/write is an entitlement grade provisioned at the identity
         *     provider; this is administration of the workspace itself. Keeping the two
         *     apart is what stops a third authorisation source appearing.
         * @enum {string}
         */
        WorkspaceRole: "owner" | "member";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserRead"];
                };
            };
        };
    };
    listMyWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipRead"][];
                };
            };
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renameWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    addWorkspaceMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    removeWorkspaceMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listExampleItems: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createExampleItem: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExampleItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getExampleItem: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: number | null;
            };
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    databaseEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseEnvironmentResponse"];
                };
            };
        };
    };
}
