/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description List the people this app has seen, for choosing who to grant membership to.
         *
         *     The app is not a directory — the identity provider is one — and this is
         *     not an attempt to be: a person appears only once they have signed in, and
         *     the projection is the three fields a picker needs. It exists because a
         *     grant names a user id (``POST /api/workspaces/{id}/members``), and an
         *     owner has to be able to find that id somewhere other than the database.
         *     An account admitted only to a room has nobody to grant a seat to, and is
         *     refused (`entitlements.require_app_module`).
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current User
         * @description Return the caller's own user record and this request's entitlements.
         *
         *     The SPA calls this once at startup to populate its auth store. The only
         *     other view of people here is the grant picker's summary above; there is
         *     no route to read another person's full record.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Workspaces
         * @description List the workspaces the caller belongs to, with their role in each.
         *
         *     Always at least one — every user is provisioned a personal workspace on first
         *     sight. The SPA calls this at startup and renders a switcher only when the
         *     list has more than one entry.
         */
        get: operations["listMyWorkspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Workspace
         * @description Create a workspace. The caller becomes its owner.
         */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename Workspace
         * @description Rename a workspace. Owner only. The slug is stable and does not follow.
         */
        patch: operations["renameWorkspace"];
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Members
         * @description List who shares a workspace. Any member may look.
         *
         *     Membership, not ownership, is the gate: the people whose data you share are
         *     not a secret from you. A non-member gets the same 403 a non-owner gets from
         *     the routes below, so the answer never confirms a workspace exists.
         */
        get: operations["listWorkspaceMembers"];
        put?: never;
        /**
         * Add Member
         * @description Grant someone membership of a workspace. Owner only.
         *
         *     This is the act the whole primitive exists for: sharing is a grant somebody
         *     makes, never something the app infers from two people using the same proxy.
         */
        post: operations["addWorkspaceMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Member
         * @description Retract someone's membership. Owner only.
         *
         *     Their rows stay with the workspace and their attribution stays on them; only
         *     the grant goes.
         */
        delete: operations["removeWorkspaceMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description List the people this app has seen, newest first.
         *
         *     A projection of the local user records, not a directory: the identity
         *     provider is the directory, and a person appears here only once they have
         *     signed in.
         */
        get: operations["adminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Update a user's local standing — today, only the active flag.
         */
        patch: operations["adminUpdateUser"];
        trace?: never;
    };
    "/api/feedback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Feedback
         * @description Record a report and file it as a GitHub issue in the background.
         *
         *     The row is created and committed before filing starts, so a slow or failed
         *     GitHub call never turns into a 5xx for the person who just reported a
         *     problem — `service.file_issue` records the outcome on the row instead.
         */
        post: operations["createFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feedback
         * @description Return one feedback report. Admin only.
         *
         *     Raises:
         *         NotFoundError: no such report exists.
         */
        get: operations["getFeedback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/{report_id}/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feedback Screenshot
         * @description Return the screenshot PNG bytes captured with this report.
         *
         *     Raises:
         *         NotFoundError: no such report exists, or it carries no screenshot.
         */
        get: operations["getFeedbackScreenshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description The newest-raised alerts, with the total and unread counts of all of them.
         */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Alert Read
         * @description Mark one alert read.
         *
         *     Raises:
         *         NotFoundError: no such alert exists.
         */
        post: operations["markAlertRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Dismiss Alert
         * @description Dismiss one alert. It returns, unread, if its producer raises it again.
         *
         *     Raises:
         *         NotFoundError: no such alert exists.
         */
        delete: operations["dismissAlert"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings Document
         * @description The JSON Schema, the effective values, and their declared defaults.
         *
         *     Everything `<SchemaForm>` needs to render the page, and everything the
         *     "overridden from default" panel needs beside it — which keys are
         *     overridden is left for the frontend to derive from `value`/`defaults`.
         */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Setting
         * @description Set `key`'s override to `data.value`.
         *
         *     Raises:
         *         NotFoundError: nothing declared `key`.
         *         ValidationError: the value fails the declared type, bounds, choices,
         *             or (for `model_alias`) a reachable gateway's own alias list.
         */
        patch: operations["updateSetting"];
        trace?: never;
    };
    "/api/settings/{key}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Setting
         * @description Delete `key`'s override, reverting it to its declared default.
         *
         *     Raises:
         *         NotFoundError: nothing declared `key`.
         */
        post: operations["resetSetting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description The append-only change log, newest first — who changed what, when.
         */
        get: operations["listSettingHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rooms
         * @description The rooms this app offers that this caller is granted; none when the app offers none.
         */
        get: operations["listRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/rooms/{room_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Ask the room's agent, streaming its events; JSON, or multipart with `files[]`.
         *
         *     The stream opens by naming the conversation. Refused before it opens:
         *     404 for a `resume` that is not this person's conversation in this room,
         *     409 while that conversation is being answered, 429 once today's
         *     allowance is spent.
         */
        post: operations["askRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/rooms/{room_id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description This person's conversations in the room, most recently active first.
         */
        get: operations["listRoomConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/rooms/{room_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Document
         * @description A document a library room cited, section by section; absent outside the room's collections.
         */
        get: operations["getRoomDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read
         * @description The conversation, every question asked, each with the answer the agent holds.
         */
        get: operations["getConversation"];
        put?: never;
        post?: never;
        /**
         * Delete
         * @description Forget the conversation: the agent's transcript first, then the row, so a failure leaves it listed.
         */
        delete: operations["deleteConversation"];
        options?: never;
        head?: never;
        /** Rename */
        patch: operations["renameConversation"];
        trace?: never;
    };
    "/api/agent/conversations/{conversation_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export
         * @description The conversation as Markdown, as a file to keep.
         */
        get: operations["exportConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/conversations/{conversation_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop
         * @description End the answer being written, from whichever worker holds it. Nothing when none is.
         */
        post: operations["stopConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/conversations/{conversation_id}/turns/{turn}/mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Mark
         * @description Mark answer `turn` (its place in the conversation as read) helpful or not, in a library room.
         *
         *     The page counts every question asked; the library counts the answers it
         *     holds. This maps one onto the other, so a question stopped before the
         *     agent took it does not shift the mark onto a neighbour.
         */
        put: operations["markAnswer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/conversations/{conversation_id}/turns/{turn}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Share
         * @description Share answer `turn` read-only with whoever may enter this room; nothing is shared until asked.
         *
         *     A settled answer only: one the agent holds, and not the one still being
         *     written. Its `shared` is the page that reads it.
         */
        put: operations["shareAnswer"];
        post?: never;
        /**
         * Unshare
         * @description Stop sharing answer `turn`: its link answers as one never shared.
         */
        delete: operations["unshareAnswer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/rooms/{room_id}/answers/{conversation_id}/{turn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Shared
         * @description A shared answer, read-only: the question, the answer and its sources.
         */
        get: operations["readSharedAnswer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quota
         * @description Today's allowance across every room.
         */
        get: operations["getAgentQuota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/{persona}/jobs/{job_id}/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Watch Job
         * @description Watch `job_id`'s events from the first, then follow them until its run settles, from any worker.
         *
         *     The same frames a room's ask streams, so `@poodle64/librarian` renders
         *     either with one code path.
         *
         *     Raises:
         *         NotFoundError: no such job, or it belongs to a different workspace
         *             or persona (`jobs.authorize`, one answer for all three, checked
         *             before the stream opens).
         */
        get: operations["watchAgentJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/{persona}/jobs/{job_id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Message Job
         * @description Send `request.text` to `job_id`: onto its stdin while it works, a resumed run once it has finished.
         */
        post: operations["messageAgentJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/{persona}/jobs/{job_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Job
         * @description Stop `job_id`. A no-op once it has already finished on its own.
         */
        post: operations["stopAgentJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/example/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Items
         * @description List the example items in the caller's workspace.
         */
        get: operations["listExampleItems"];
        put?: never;
        /**
         * Create Item
         * @description Create a new example item.
         */
        post: operations["createExampleItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/example/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Item
         * @description Get a single example item by id.
         */
        get: operations["getExampleItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Report liveness and verify the database dependency.
         *
         *     Pings the database with `SELECT 1`; a 503 is the only outcome that
         *     should fail a load balancer's health check, so every other dependency
         *     this app grows should degrade the body, never this status code.
         *
         *     Raises:
         *         ServiceUnavailableError: the database is unreachable (503).
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/database-environment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Database Environment
         * @description Report what the database this backend is bound to declares itself to be.
         *
         *     The one thing a caller talking to this backend over HTTP — rather than
         *     holding a connection of its own — can ask to find out what it is really
         *     about to write to. `db/environment.py`'s reasoning applies unchanged:
         *     unstamped or unreachable reads as production, fail-closed.
         *
         *     No auth dependency, matching /health: a caller that cannot yet tell which
         *     database it has reached is in no position to authenticate against it, and
         *     the answer names an environment, never a host or a credential.
         */
        get: operations["databaseEnvironment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminUserList
         * @description One page of the app's local user records.
         */
        AdminUserList: {
            /** Users */
            users: components["schemas"]["AdminUserRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * AdminUserRead
         * @description A user as the admin area exposes them.
         *
         *     A superset of ``UserRead`` deliberately NOT derived from it: the two views
         *     answer different questions ("who am I" versus "who has this app seen"), and
         *     coupling them means a field added for one silently widens the other.
         *     ``authentik_uid`` stays absent here too — the operator correlates people in
         *     Authentik by username or email, and echoing the provider's key back widens
         *     what a compromised admin session learns.
         */
        AdminUserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Seen At */
            last_seen_at: string | null;
        };
        /**
         * AdminUserUpdate
         * @description Request body for updating a user's local standing.
         *
         *     ``is_active`` is the only mutable field: everything else on the row is the
         *     identity provider's, re-synced from the headers on every request, so a
         *     local edit would be overwritten on the person's next sign-in.
         */
        AdminUserUpdate: {
            /** Is Active */
            is_active: boolean;
        };
        /**
         * AgentJobMessageRequest
         * @description A message to an app-started job (`api/agent/jobs.py`), while it is
         *     running or after it has finished — `jobs.send_message` decides which.
         */
        AgentJobMessageRequest: {
            /** Text */
            text: string;
        };
        /**
         * AlertList
         * @description The newest alerts, and the counts the bell's badge needs beyond them.
         */
        AlertList: {
            /** Alerts */
            alerts: components["schemas"]["AlertRead"][];
            /** Total */
            total: number;
            /** Unread */
            unread: number;
        };
        /**
         * AlertRead
         * @description An alert as the bell shows it.
         *
         *     This and `AlertList` are `@poodle64/ui`'s `AlertBell` contract, not this
         *     app's choice: renaming a field here without changing the package silently
         *     empties every app's bell.
         */
        AlertRead: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Body */
            body: string | null;
            /** Link */
            link: string | null;
            /**
             * Raised At
             * Format: date-time
             */
            raised_at: string;
            /** Read At */
            read_at: string | null;
        };
        /** ConversationRead */
        ConversationRead: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /** Answering Since */
            answering_since?: string | null;
            /** Turns */
            turns: components["schemas"]["StoredTurn"][];
        };
        /** ConversationSummary */
        ConversationSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /** Answering Since */
            answering_since?: string | null;
        };
        /**
         * CurrentUserRead
         * @description The caller's own record, plus the entitlements this request carried.
         *
         *     Entitlements are NOT persisted — they arrive in a header on every request and
         *     are true only of the request that carried them. Serving them here is what lets
         *     the SPA hide a module the caller cannot reach; it is a convenience for the UI,
         *     never the gate. The gate is ``require_module()`` on the server.
         */
        CurrentUserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string | null;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Entitlements */
            entitlements: string[];
        };
        /**
         * DatabaseEnvironmentResponse
         * @description What the running backend's database declares itself to be.
         */
        DatabaseEnvironmentResponse: {
            /** Environment */
            environment: string;
        };
        /** DocumentRead */
        DocumentRead: {
            /** Title */
            title: string;
            /** Sections */
            sections: components["schemas"]["DocumentSection"][];
        };
        /** DocumentSection */
        DocumentSection: {
            /** Anchor */
            anchor: string;
            /** Heading */
            heading: string;
            /** Text */
            text: string;
        };
        /**
         * ExampleItemCreate
         * @description Request body for creating an ExampleItem.
         */
        ExampleItemCreate: {
            /** Title */
            title: string;
            /** Body */
            body?: string | null;
        };
        /**
         * ExampleItemRead
         * @description Response schema for ExampleItem (excludes internal DB columns).
         */
        ExampleItemRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Body */
            body: string | null;
        };
        /**
         * FeedbackCreate
         * @description A report as `@poodle64/ui`'s `ReportWidget` POSTs it.
         *
         *     Shape and field names are the package's contract, not this app's choice —
         *     changing one here without changing the widget silently breaks every app
         *     that has taken it.
         */
        FeedbackCreate: {
            /** Message */
            message: string;
            /** Route */
            route: string;
            /** User Agent */
            user_agent: string;
            viewport: components["schemas"]["Viewport"];
            /** Session Id */
            session_id: string;
            /** Screenshot */
            screenshot?: string | null;
        };
        /**
         * FeedbackCreateResponse
         * @description The one thing `ReportWidget`'s `onSubmitted(id)` needs.
         */
        FeedbackCreateResponse: {
            /** Id */
            id: number;
        };
        /**
         * FeedbackRead
         * @description A feedback report as the admin surface reads it back.
         *
         *     No screenshot field: the bytes are served separately
         *     (`GET /api/feedback/{id}/screenshot`), so a caller reading the list never
         *     pays for an image it may not want.
         */
        FeedbackRead: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Route */
            route: string;
            /** User Agent */
            user_agent: string;
            /** Viewport Width */
            viewport_width: number;
            /** Viewport Height */
            viewport_height: number;
            /** Session Id */
            session_id: string;
            /** Message */
            message: string;
            status: components["schemas"]["FeedbackStatus"];
            /** Issue Url */
            issue_url: string | null;
            /** Error */
            error: string | null;
        };
        /**
         * FeedbackStatus
         * @description Where a report stands with the GitHub issue tracker.
         *
         *     Two values only, deliberately: v1 does no triage, so there is nothing
         *     between "not filed yet" and "filed". A row that fails to file stays
         *     RECEIVED with `error` set, rather than gaining a third state — the retry
         *     is a human re-reading `error`, not a state machine.
         * @enum {string}
         */
        FeedbackStatus: "received" | "filed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response body.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Revision */
            revision: string;
            /** Environment */
            environment: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** MarkRequest */
        MarkRequest: {
            /** Helpful */
            helpful: boolean;
            /** Note */
            note?: string | null;
        };
        /**
         * MemberAdd
         * @description Request body for granting someone membership of a workspace.
         *
         *     Identified by the app's own user id rather than an Authentik uid: the caller
         *     granting access is choosing from people the app already knows, and accepting
         *     a provider key here would let a client mint a membership for an identity the
         *     app has never authenticated.
         */
        MemberAdd: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** @default member */
            role: components["schemas"]["WorkspaceRole"];
        };
        /**
         * MemberRead
         * @description One member OF a workspace, with their standing in it.
         *
         *     The other direction from ``MembershipRead``: that is one person's
         *     workspaces, this is one workspace's people — what the members surface
         *     renders, and what an owner reads before granting or retracting.
         */
        MemberRead: {
            user: components["schemas"]["MemberUserRead"];
            role: components["schemas"]["WorkspaceRole"];
        };
        /**
         * MemberUserRead
         * @description The person a membership belongs to, as the members list shows them.
         *
         *     id, username and display name only — enough to render a row and to name
         *     who is being removed. Email and last-seen are the person's own
         *     (``GET /api/users/me``) and the admin area's, never every fellow member's.
         */
        MemberUserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string | null;
        };
        /**
         * MembershipRead
         * @description One of the caller's memberships, with the workspace it grants.
         *
         *     This is what the SPA's workspace switcher renders, and what tells it whether
         *     to render at all: a caller with one membership never sees a switcher.
         */
        MembershipRead: {
            workspace: components["schemas"]["WorkspaceRead"];
            role: components["schemas"]["WorkspaceRole"];
        };
        /** QuotaRead */
        QuotaRead: {
            /** Limit */
            limit: number;
            /** Remaining */
            remaining: number;
            /** Exempt */
            exempt: boolean;
            /** Reached */
            reached: boolean;
            /**
             * Resets At
             * Format: date-time
             */
            resets_at: string;
            /** Support Url */
            support_url?: string | null;
        };
        /** RenameRequest */
        RenameRequest: {
            /** Title */
            title: string;
        };
        /** RoomRead */
        RoomRead: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Blurb */
            blurb: string;
            /** Examples */
            examples: string[];
            /** Not Held */
            not_held: string;
            /** Sources */
            sources: string[];
            /** Library */
            library: boolean;
            /** Documents To */
            documents_to?: string | null;
        };
        /**
         * SettingChangeRead
         * @description One row of the append-only history — who changed what, when.
         */
        SettingChangeRead: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Old Value */
            old_value: boolean | number | string | null;
            /** New Value */
            new_value: boolean | number | string;
            /** Changed By */
            changed_by: string | null;
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
        };
        /**
         * SettingHistoryList
         * @description One page of the settings history, newest first.
         */
        SettingHistoryList: {
            /** Changes */
            changes: components["schemas"]["SettingChangeRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * SettingRead
         * @description One setting's effective state, returned after a write or a reset.
         */
        SettingRead: {
            /** Key */
            key: string;
            /** Value */
            value: boolean | number | string;
            /** Default */
            default: boolean | number | string;
            /** Overridden */
            overridden: boolean;
        };
        /**
         * SettingUpdate
         * @description Request body for `PATCH /api/settings/{key}` — one field's next value.
         */
        SettingUpdate: {
            /** Value */
            value: boolean | number | string;
        };
        /**
         * SettingsDocument
         * @description What `<SchemaForm>` needs to render the whole page: a JSON Schema and a value.
         *
         *     No UI Schema travels alongside it — `@poodle64/ui/schema-form` generates
         *     its own layout from the JSON Schema alone (`docs/design/settings.md`
         *     §The page), which is the only mode in which a declared setting cannot be
         *     missing from the rendered form.
         */
        SettingsDocument: {
            /** Schema */
            schema: {
                [key: string]: unknown;
            };
            /** Value */
            value: {
                [key: string]: boolean | number | string;
            };
            /** Defaults */
            defaults: {
                [key: string]: boolean | number | string;
            };
        };
        /** StoredTurn */
        StoredTurn: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** At */
            at: string | null;
            /**
             * Citations
             * @default []
             */
            citations: {
                [key: string]: unknown;
            }[];
            /** Kind */
            kind?: string | null;
            /** Depth */
            depth?: ("quick" | "thorough") | null;
            /** Shared */
            shared?: string | null;
        };
        /**
         * UserSummary
         * @description A person as the grant picker shows them: the minimum needed to choose one.
         *
         *     id, username and display name — nothing else. This is the ONE projection
         *     of other people the app serves to an ordinary member, and it exists for
         *     exactly one act: an owner choosing, from the people the app already knows,
         *     who to grant workspace membership to (`rules-library/platform/tenancy.md`
         *     — sharing is a grant an owner makes). Email and last-seen stay with the
         *     admin area, which is gated separately.
         */
        UserSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Viewport
         * @description The reporting browser's window size, for reproducing what the user saw.
         */
        Viewport: {
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /**
         * WorkspaceCreate
         * @description Request body for creating a workspace. The creator becomes its owner.
         */
        WorkspaceCreate: {
            /** Name */
            name: string;
        };
        /**
         * WorkspaceRead
         * @description A workspace as the API exposes it.
         */
        WorkspaceRead: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /**
         * WorkspaceRename
         * @description Request body for renaming a workspace. Owner only.
         */
        WorkspaceRename: {
            /** Name */
            name: string;
        };
        /**
         * WorkspaceRole
         * @description A member's standing IN a workspace — never what they may do in a module.
         *
         *     Module read/write is an entitlement grade provisioned at the identity
         *     provider; this is administration of the workspace itself. Keeping the two
         *     apart is what stops a third authorisation source appearing.
         * @enum {string}
         */
        WorkspaceRole: "owner" | "member";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserRead"];
                };
            };
        };
    };
    listMyWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipRead"][];
                };
            };
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renameWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listWorkspaceMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    addWorkspaceMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    removeWorkspaceMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: number;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                /** @description Page size */
                limit?: number;
                /** @description Page offset */
                offset?: number;
                /** @description Case-insensitive substring of username, display name or email */
                search?: string | null;
                /** @description Filter by the local active flag */
                active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adminUpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getFeedbackScreenshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                /** @description How many of the newest to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markAlertRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismissAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDocument"];
                };
            };
        };
    };
    updateSetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resetSetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSettingHistory: {
        parameters: {
            query?: {
                /** @description Page size */
                limit?: number;
                /** @description Page offset */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingHistoryList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"][];
                };
            };
        };
    };
    askRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRoomConversations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRoomDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renameConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stopConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn: number;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shareAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn: number;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredTurn"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unshareAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn: number;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readSharedAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn: number;
                conversation_id: string;
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredTurn"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getAgentQuota: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaRead"];
                };
            };
        };
    };
    watchAgentJob: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: number | null;
            };
            path: {
                persona: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    messageAgentJob: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: number | null;
            };
            path: {
                persona: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentJobMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stopAgentJob: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: number | null;
            };
            path: {
                persona: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listExampleItems: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createExampleItem: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExampleItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getExampleItem: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: number | null;
            };
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    databaseEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseEnvironmentResponse"];
                };
            };
        };
    };
}
