import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { existsSync, readFileSync, statSync } from 'node:fs';
import { extname, join } from 'node:path';
const root = 'packages/console/build';
const MIME = { '.html':'text/html; charset=utf-8', '.js':'text/javascript; charset=utf-8', '.css':'text/css; charset=utf-8', '.json':'application/json', '.svg':'image/svg+xml', '.woff2':'font/woff2' };
const server = createServer((req,res)=>{ const p=(req.url??'/').split('?')[0]; let f=join(root, p==='/'?'index.html':p); if(!existsSync(f)||statSync(f).isDirectory()){const i=join(f,'index.html'); f=existsSync(i)?i:join(root,'index.html');} res.writeHead(200,{'Content-Type':MIME[extname(f)]??'application/octet-stream'}); res.end(readFileSync(f)); });
await new Promise(r=>server.listen(4183,r));
const b = await chromium.launch();
const page = await b.newPage({ viewport:{width:1440,height:900} });
await page.goto('http://localhost:4183/librarian?state=answer', { waitUntil:'domcontentloaded' });
await page.waitForSelector('textarea');
await page.waitForTimeout(1200);
console.log('PRE HTML:', (await page.locator('pre').first().innerHTML()).slice(0,600));
console.log('PRE CLASS:', await page.locator('pre').first().getAttribute('class'));
console.log('PRE STYLE:', await page.locator('pre').first().evaluate(el => { const c = getComputedStyle(el); return { ws: c.whiteSpace, td: c.textDecorationLine, color: c.color }; }));
console.log('SPAN STYLE:', await page.locator('pre span').first().evaluate(el => { const c = getComputedStyle(el); return { td: c.textDecorationLine, color: c.color }; }));
console.log('TABLE box:', await page.locator('table').first().evaluate(el => ({ sw: el.scrollWidth, cw: el.clientWidth })));
console.log('composer h:', await page.locator('textarea').evaluate(el => el.getBoundingClientRect().height));
await b.close(); server.close();
